<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <PackageId>Solentik.Paystack.AspNetCore</PackageId>
    <Version>1.0.3</Version>
    <Authors>Solentik</Authors>
    <Company>Solentik</Company>
    <Description>ASP.NET Core webhook routing and typed event handlers for Solentik.Paystack.</Description>
    <PackageTags>paystack;payments;webhooks;aspnetcore</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://paystack.solentik.com/dotnet/introduction.html</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>icon.png</PackageIcon>
    <RepositoryUrl>https://github.com/Solentik-Com/dotnet-paystack</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
    <None Include="..\..\icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\Solentik.Paystack\Solentik.Paystack.csproj" />
  </ItemGroup>
</Project>
